### ISSUE TITLE
Row 안에 Container 로 묶지 않았을때 에러남

### ISSUE THREAD

**Issue by probepark** [probepark/flutter-study#1]
https://github.com/probepark/flutter-study/blob/1cdb5edea55baa664a42ffbca78d1fc0f10f60a6/basic/lib/main.dart#L86

**Comment by AlexMoon90** [comment]
BusinessCard()내 Column을 Expanded 묶으시면 되지 않을까요?

**Comment by probepark** [comment]
그생각을 못했네요. ㅋㅋ 감사합니다.
